### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by michaelpfaff** [djensen47/nodebb-plugin-dice-bot#1]
Hi! I've installed this plugin on my NodeBB forum but not sure how to activate the bot. Can you give me a hint? Thanks!

**Comment by djensen47** [comment]
This plugin is an unfinished work in progress.

You'll have to make some manual changes to the code to get it to work. 
- Create an account for the Dice Bot
- In the dice.js file, change `BOT_UID` to the id of the Dice Bot account
-  In a post type `[dice 1d6]` or `[dice 3d10 5d6]` and so on

Here's an example of it in action:
http://forums.axisandallies.org/topic/4/hello-again

**Comment by michaelpfaff** [comment]
Awesome! Thanks so much! 

One other question: when I download the .zip it doesn't include the /src/dice.js. Do I need to manually add that? Sorry for the questions. This is my first manual install for a NodeBB plugin.

**Comment by djensen47** [comment]
It's in there. It's located in the `src` directory.

**Comment by michaelpfaff** [comment]
Hmmm. Yeah, I'm not seeing it when I download from Github. However, I can just upload to the /nodebb/src directory with the BOT UID changed right? Or, should it go in the main plugin folder?

**Comment by michaelpfaff** [comment]
Thanks for your help, btw. Very much appreciated.

**Comment by michaelpfaff** [comment]
Nvm, man! The zip package I was using was messing up the archive.

**Comment by michaelpfaff** [comment]
Okay, I've got everything installed. Change the BOT UID to the ID for the bot account, but still not working. Any other options for me to try?

**Comment by michaelpfaff** [comment]
Wondering if this might have something to do with it: 

`19/1 23:05:15 [6633] - error: [plugins] NodeBB encountered a problem while loading plugins ENOENT: no such                                                                        file or directory, scandir '/var/www/html/community/node_modules/nodebb-plugin-dice-bot/languages'
19/1 23:05:15 [6633] - error:  Error: ENOENT: no such file or directory, scandir '/var/www/html/community/                                                                       node_modules/nodebb-plugin-dice-bot/languages'
    at Error (native)
[cluster] Child Process (6633) has exited (code: 0, signal: null)
19/1 23:05:15 [6633] - error: [plugins] NodeBB encountered a problem while loading plugins ENOENT: no such                                                                        file or directory, scandir '/var/www/html/community/node_modules/nodebb-plugin-dice-bot/languages'
19/1 23:05:15 [6633] - error:  Error: ENOENT: no such file or directory, scandir '/var/www/html/community/                                                                       node_modules/nodebb-plugin-dice-bot/languages'
    at Error (native)`

**Comment by michaelpfaff** [comment]
Think it's this line in plugin.json? 

`"languages": "languages",`

**Comment by djensen47** [comment]
Sure, try removing that line and see what happens.

**Comment by michaelpfaff** [comment]
That worked! Woot! Plugin functions!

**Comment by michaelpfaff** [comment]
Thanks so much man!

**Comment by djensen47** [comment]
No problem.
