### ISSUE TITLE
Modifier adds to each die

### ISSUE THREAD

**Issue by michaelpfaff** [djensen47/nodebb-plugin-dice-bot#2]
Did you intend for the modifier to add to each die? 

So:

[dice 3d6+3] and all 6s rolled outputs 3d6+3: 9, 9, 9 right? 

Is there any way to output a total that sums each die and the modifier once? 

For example: 

[dice 3d6+3] and all 6s rolled instead outputs 3d6+3: 6, 6, 6, 3 = 21

Or maybe just: 

[dice 3d6+3] and all 6s rolled instead outputs 3d6+3: 21

**Comment by djensen47** [comment]
Yeah, I see now that is incorrect.

For Axis & Allies, all of the dice rolls displayed and modifiers are not needed.

I like a slight variation on one of your ideas:
**3d6+3:** 6, 6, 6 +3 = **21**

**Comment by michaelpfaff** [comment]
Love your variation and probably makes the most sense! That an easy fix or will the code have to be changed a lot?

**Comment by djensen47** [comment]
It should be easy but I don't have a ton of time right now.

**Comment by michaelpfaff** [comment]
Hi Dave! I hate to bother you with this, but I've been working on it off and on for over a month now and just can't quite figure out how to get it to add the modifier to the total and then output what we suggested above (I'm trying to learn Javascript, but still crazy novice). 

Was wondering if I could buy you a beer or two to help refine the code to fix this? 

If not, no biggie! Just thought I'd try to bribe you! Thanks man.
